[package]
name = "safehouse-server"
version = "0.1.0"
authors = ["Leon Hartley <dev@leonh.net>"]

[dependencies]
websocket = "0.20.2"
rocket = "0.3.8"
rocket_codegen = "0.3.8"
rocket_contrib = "0.3.8"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"